# if country has alphanumeric support with Twilio, return True. Else false.
def phone_country_alphanumeric(phone: str) -> bool:
    from phonenumbers.phonenumberutil import region_code_for_country_code

    # this list represents all countries without alphanumeric support or you need to apply for it.
    nonalphanumeric_countries = {
        "AS": "American Samoa",
        "AR": "Argentina",
        "AM": "Armenia",
        "BS": "Bahamas",
        "BE": "Belgium",
        "BY": "Belarus",
        "BZ": "Belize",
        "CA": "Canada",
        "KY": "Cayman Islands (UK)",
        "TD": "Chad",
        "CL": "Chile",
        "CN": "China",
        "CO": "Colombia",
        "CG": "Congo (Republic of the Congo)",
        "CR": "Costa Rica",
        "CU": "Cuba",
        "CZ": "Czech Republic",
        "DO": "Dominican Republic",
        "EC": "Ecuador",
        "EG": "Egypt",
        "SV": "El Salvador",
        "GF": "French Guiana",
        "GU": "Guam",
        "GT": "Guatemala",
        "HN": "Honduras",
        "HU": "Hungary",
        "IN": "India",
        "ID": "Indonesia",
        "IR": "Iran",
        "IL": "Israel",
        "JP": "Japan",
        "JO": "Jordan",
        "KZ": "Kazakhstan",
        "KE": "Kenya",
        "KW": "Kuwait",
        "KG": "Kyrgyzstan",
        "LB": "Lebanon",
        "MW": "Malawi",
        "MY": "Malaysia",
        "ML": "Mali",
        "MX": "Mexico",
        "MC": "Monaco",
        "MA": "Morocco",
        "MM": "Myanmar",
        "NA": "Namibia",
        "NR": "Nauru",
        "NP": "Nepal",
        "NZ": "New Zealand",
        "NI": "Nicaragua",
        "OM": "Oman",
        "PK": "Pakistan",
        "PS": "Palestine",
        "PA": "Panama",
        "PE": "Peru",
        "PH": "Philippines",
        "PR": "Puerto Rico",
        "QA": "Qatar",
        "RU": "Russia",
        "SA": "Saudi Arabia",
        "ZA": "South Africa",
        "KR": "South Korea",
        "LK": "Sri Lanka",
        "SD": "Sudan",
        "SY": "Syria",
        "TW": "Taiwan",
        "TZ": "Tanzania",
        "TH": "Thailand",
        "TN": "Tunisia",
        "TR": "Turkey",
        "UA": "Ukraine",
        "AE": "United Arab Emirates",
        "US": "United States",
        "UY": "Uruguay",
        "VE": "Venezuela",
        "YE": "Yemen",
        "ZM": "Zambia",
        "ZW": "Zimbabwe",
    }
    pn = phonenumbers.parse(phone)
    if region_code_for_country_code(pn.country_code) in nonalphanumeric_countries:
        return False
    else:
        return True
